version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_USER: pgsqluser
      POSTGRES_PASSWORD: pgsqlpass
      POSTGRES_DB: destdb
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "54320:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mariadb:
    image: mariadb:11.8
    container_name: mariadb-test
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: sourcedb
      MARIADB_USER: mariadbuser
      MARIADB_PASSWORD: mariadbpass
    ports:
      - "33060:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  postgres-data:
    driver: local
  mariadb-data:
    driver: local
